### ISSUE TITLE
InheritDoc faults when encountering a native dll

### ISSUE THREAD

**Issue by rjmurillo** [firesharkstudios/InheritDoc#1]
In the Microsoft/WindowsCommunityToolkit we build several types of assemblies for both .NET and Native. Once our native assemblies are built, we cannot run InheritDoc due to an unhandled exception

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'Microsoft.Toolkit.Uwp.Input.GazeInteraction.dll' or one of its dependencies. The module was expected to contain an assembly manifest. ---> System.BadImageFormatException: Could not load file or assembly 'Microsoft.Toolkit.Uwp.Input.GazeInteraction.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at InheritDocLib.InheritDocUtil.LoadAssemblyDocuments(ICollection`1 assemblyFiles, Action`2 logger) in C:\Users\Kent\Documents\Visual Studio 2017\Projects\InheritDoc\InheritDocLib\InheritDocUtil.cs:line 105
   at InheritDocLib.InheritDocUtil.Run(String basePath, String xmlDocFileNamePatterns, String excludeTypeNamePatterns, Boolean overwriteExisting, Action`2 logger) in C:\Users\Kent\Documents\Visual Studio 2017\Projects\InheritDoc\InheritDocLib\InheritDocUtil.cs:line 47
   at InheritDoc.Program.Main(String[] args) in C:\Users\Kent\Documents\Visual Studio 2017\Projects\InheritDoc\InheritDoc\Program.cs:line 19
```

I would expect to either:
 - Specify a DLL to exclude, and/or
 - Have the error logged and the documentation process continue

**Comment by firesharkstudios** [comment]
I've released v1.1.1 to fix this issue.  Thanks for opening the issue..
